export default {
  install(Vue, options) {
    Vue.prototype.$localization = {
      de: {
        all: 'Alle',
        authority: 'Art der Prägung',
        authority_group: 'Stamm',
        authority_person: 'Herrscher',
        axis: 'Achse',
        basics: 'Basisdaten',
        bbaw: 'Berlin-Brandenburgische Akademie der Wissenschaften',
        bibliography: 'Bibliographie',
        centerhole: 'Zentrierloch',
        citations: 'Zitierungen',
        close: 'Schließen',
        coin: 'Münze',
        coin_representing: 'Repräsentierende Münze',
        coins: 'Münzen',
        coins_latest_unpublished: 'Ihre unpublizierten Münzen',
        collection_id: 'Sammlungs-Nr.',
        comment: 'Kommentar',
        comment_private: 'Interner Kommentar',
        comment_public: 'Öffentlicher Kommentar',
        comments: 'Kommentare',
        controlmark: 'Kontrollzeichen',
        controlmarks: 'Kontrollzeichen',
        copyright_author: 'Author',
        copyright_data: 'Forschungsdaten',
        copyright_header: 'Lizenzierung',
        copyright_sw: 'Forschungssoftware',
        countermark: 'Gegenstempel',
        created_at: 'Erstellt am',
        data_imported: 'Importdaten',
        data_protection: 'Datenschutz',
        date: 'Datierung',
        denomination: 'Denomination',
        depiction: 'Darstellung',
        description: 'Beschreibung',
        description_private: 'Interne Beschreibung',
        design: 'Beschreibung',
        designs: 'Beschreibungen',
        details: 'Details',
        diameter: 'Durchmesser',
        external_data: 'Externe Daten',
        find_circumstances: 'Fundumstände',
        findspot: 'Fundort',
        findspots: 'Fundorte',
        general: 'Allgemein',
        groups: 'Gruppen',
        hoard: 'Hort',
        hoards: 'Horte',
        image: 'Bild',
        images: 'Bilder',
        imageset: 'Bildpaar',
        imagesets: 'Bildpaare',
        imprint_header: 'Impressum',
        increase: 'Zuwachs',
        individuals: 'Individuen',
        issue: 'Ausgabe',
        issuer: 'Beamter',
        joined_at: 'Registriert am',
        legend: 'Legende',
        legends: 'Legenden',
        link: 'Verknüpfung',
        link_type_inheriting: 'Vererbenden Typ verknüpfen',
        link_type_noninheriting: 'Weitere Typen verknüpfen',
        linked: 'Verknüpfte',
        linked_coins: 'Verknüpfte Münzen',
        linked_plural: 'Verknüpfte',
        linked_types: 'Verknüpfte Typen',
        links: 'Weblinks',
        literature: 'Literatur',
        literature_type: 'Typ Literatur',
        login_last: 'Letzter Login',
        material: 'Material',
        mint: 'Münzstätte',
        mints: 'Münzstätten',
        miscellaneous: 'Sonstiges',
        moesia_inferior: 'Moesia Inferior',
        monogram: 'Monogramm',
        monograms: 'Monogramme',
        mysia: 'Mysien',
        name_private: 'Interner Name',
        objectgroups: 'Objektgruppen',
        obverse: 'Obvers',
        owner: 'Besitzer',
        owner_original: 'Besitzer (Original)',
        owner_reproduction: 'Besitzer (Repro)',
        owners: 'Besitzer',
        period: 'Epoche',
        person: 'Person',
        persons: 'Personen',
        plastercast_id: 'Gips-Nr.',
        private: 'intern',
        production: 'Produktion',
        provenience: 'Provenienz',
        public: 'öffentlich',
        published: 'publiziert',
        reference: 'Referenz',
        references: 'Referenzen',
        remarks: 'Anmerkungen',
        reverse: 'Revers',
        source: 'Quelle',
        standard: 'Standard',
        statistics_general: 'Allgemeine Statistik',
        statistics_personal: 'Persönliche Statistik',
        superuser_description: 'Root darf alles',
        symbol: 'Symbol',
        symbols: 'Symbole',
        technical_parameters: 'Technische Parameter',
        thrace: 'Thrakien',
        troas: 'Troas',
        type: 'Typ',
        type_inheriting: 'Vererbender Typ',
        type_variations: 'Typ-Variationen',
        types: 'Typen',
        types_latest_unpublished: 'Ihre unpublizierten Typen',
        undertype: 'Überprägung',
        updated_at: 'Geändert am',
        variations: 'Variationen',
        web_references: 'Links',
        weight: 'Gewicht',
        welcome: 'Willkommen',
        welcome_back: 'Willkommen zurück'
      },
      en: {
        all: 'All',
        authority: 'Type of Coinage',
        authority_group: 'Tribe',
        authority_person: 'Ruler',
        axis: 'Axis',
        basics: 'Basics',
        bbaw: 'Berlin Brandenburg Academy of Science and Humanities',
        bibliography: 'Bibliography',
        centerhole: 'Centerhole',
        citations: 'Citations',
        close: 'Close',
        coin: 'Coin',
        coin_representing: 'Representing Coin',
        coins: 'Coins',
        coins_latest_unpublished: 'Your latest unpublished Coins',
        collection_id: 'Collection Nr.',
        comment: 'Comment',
        comment_private: 'Private Comment',
        comment_public: 'Public Comment',
        comments: 'Comments',
        controlmark: 'Controlmark',
        controlmarks: 'Controlmarks',
        copyright_author: 'Author',
        copyright_data: 'Research Data',
        copyright_header: 'Copyright',
        copyright_sw: 'Research Software',
        countermark: 'Countermark',
        created_at: 'Created at',
        data_imported: 'Import Data',
        data_protection: 'Data Protection',
        date: 'Date',
        denomination: 'Denomination',
        depiction: 'Depiction',
        description: 'Description',
        description_private: 'Private Description',
        design: 'Design',
        designs: 'Designs',
        details: 'Details',
        diameter: 'Diameter',
        external_data: 'External Data',
        find_circumstances: 'Find Circumstances',
        findspot: 'Findspot',
        findspots: 'Findspots',
        general: 'General',
        groups: 'Groups',
        hoard: 'Hoard',
        hoards: 'Hoards',
        image: 'Image',
        images: 'Images',
        imageset: 'Image Set',
        imagesets: 'Image Sets',
        imprint_header: 'Imprint',
        increase: 'increase',
        individuals: 'Individuals',
        issue: 'Issue',
        issuer: 'Issuer',
        joined_at: 'Joined at',
        legend: 'Legend',
        legends: 'Legends',
        link: 'Link',
        link_type_inheriting: 'Link inheriting Type',
        link_type_noninheriting: 'Link additional Types',
        linked: 'Linked',
        linked_coins: 'Linked Coins',
        linked_plural: 'Linked',
        linked_types: 'Linked Types',
        links: 'Weblinks',
        literature: 'Literature',
        literature_type: 'Type Literature',
        login_last: 'Last Login',
        material: 'Material',
        mint: 'Mint',
        mints: 'Mints',
        miscellaneous: 'Miscellaneous',
        moesia_inferior: 'Moesia Inferior',
        monogram: 'Monograms',
        monograms: 'Monograms',
        mysia: 'Mysia',
        name_private: 'Private Name',
        objectgroups: 'Object Groups',
        obverse: 'Obverse',
        owner: 'Owner',
        owner_original: 'Owner (Original)',
        owner_reproduction: 'Owner (Repro)',
        owners: 'Owners',
        period: 'Period',
        person: 'Person',
        persons: 'Persons',
        plastercast_id: 'Plastercast Nr.',
        private: 'private',
        production: 'Production',
        provenience: 'Provenience',
        public: 'public',
        published: 'published',
        reference: 'Reference',
        references: 'References',
        remarks: 'Remarks',
        reverse: 'Reverse',
        source: 'Source',
        standard: 'Standard',
        statistics_general: 'General Statistics',
        statistics_personal: 'Your Statistics',
        superuser_description: 'Root can everything',
        symbol: 'Symbol',
        symbols: 'Symbols',
        technical_parameters: 'Technical Parameters',
        thrace: 'Thrace',
        troas: 'Troas',
        type: 'Type',
        type_inheriting: 'Inheriting Type',
        type_variations: 'Type Variations',
        types: 'Types',
        types_latest_unpublished: 'Your latest unpublished Types',
        undertype: 'Undertype',
        updated_at: 'Updated at',
        variations: 'Variations',
        web_references: 'Links',
        weight: 'Weight',
        welcome: 'Welcome',
        welcome_back: 'Welcome back'
      }
    }
  }
}